name: Metrics
on:
  # Schedule updates (every sunday)
  schedule: [{ cron: "0 0 * * 0" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: MiguelRobles7
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Manila
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: stroke-prediction-ml,stroke-ml-view
          plugin_languages_threshold: 0%
          repositories_affiliations: owner, contributor
